const fontListAll = [
  'Roboto Condensed',
  'Montserrat',
  'Oswald',
  'Source Sans Pro',
  'Slabo 27px',
  'Raleway',
  'PT Sans',
  'Merriweather',
  'Roboto Slab',
  'Open Sans Condensed',
  'Ubuntu',
  'Poppins',
  'Playfair Display',
  'Lora',
  'PT Serif',
  'Roboto Mono',
  'Muli',
  'Titillium Web',
  'Arimo',
  'PT Sans Narrow',
  'Noto Serif',
  'Fira Sans',
  'Nunito',
  'Inconsolata',
  'Dosis',
  'Crimson Text',
  'Indie Flower',
  'Libre Franklin',
  'Work Sans',
  'Bitter',
  'Quicksand',
  'Oxygen',
  'Fjalla One',
  'Cabin',
  'Anton',
  'Josefin Sans',
  'Rubik',
  'Libre Baskerville',
  'Hind',
  'Lobster',
  'Exo 2',
  'Arvo',
  'Patua One',
  'Karla',
  'Pacifico',
  'Yanone Kaffeesatz',
  'Abel',
  'Source Serif Pro',
  'Varela Round',
  'Shadows Into Light',
  'Merriweather Sans',
  'Ubuntu Condensed',
  'Questrial',
  'Nunito Sans',
  'Dancing Script',
  'Exo',
  'Asap',
  'Bree Serif',
  'Hind Siliguri',
  'Archivo Narrow',
  'Abril Fatface',
  'Acme',
  'Amatic SC',
  'Signika',
  'Righteous',
  'Gloria Hallelujah',
  'Kanit',
  'Comfortaa',
  'Play',
  'Cairo',
  'Teko',
  'Maven Pro',
  'Encode Sans Condensed',
  'Pathway Gothic One',
  'Rajdhani',
  'Francois One',
  'Russo One',
  'EB Garamond',
  'Crete Round',
  'Source Code Pro',
  'Rokkitt',
  'Heebo',
  'PT Sans Caption',
  'Cuprum',
  'Vollkorn',
  'Alegreya Sans SC',
  'Ropa Sans',
  'Cinzel',
  'Alegreya',
  'Catamaran',
  'Concert One',
  'Permanent Marker',
  'Old Standard TT',
  'Poiret One',
  'Hind Madurai',
  'Satisfy',
  'Great Vibes',
  'Cookie',
  'ABeeZee',
  'Courgette',
];

export default fontListAll;
